esphome:
  name: valve
  platform: ESP8266
  board: esp_wroom_02

wifi:
  ssid: "DiffurNet"
  password: !secret wifi_password

mqtt:
  broker: 192.168.10.105
  username: user
  on_message:
    topic: my/custom/topic
    qos: 0
    then:
      - logger.log: "Still executing"
#      - switch.toggle: gpio_d1

#  password: MyMQTTPassword

  # Enable fallback hotspot (captive portal) in case wifi connection fails
#  ap:
#    ssid: "Test Fallback Hotspot"
#    password: "DOrUdMrK98Q5"

#captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
#api:

#ota:

#    - switch.turn_on: some_switch

switch:
  - platform: gpio
    pin: GPIO16
    name: "Switch Name"
    inverted:  True
    id: gpio_d1

deep_sleep:
  run_duration: 10s
  sleep_duration: 1min