esphome:
  name: moisture_sensor_4
  platform: ESP8266
  board: esp_wroom_02
  on_boot:
    priority: 1000
    then:
      - script.execute: send_status

wifi:
  ssid: "DiffurNet"
  password: !secret wifi_password
#  use_address: 192.168.10.201
#  manual_ip:
#    static_ip: 192.168.10.201
#    gateway: 192.168.10.1
#    subnet: 255.255.255.0

script:
  - id: send_status
    then:
      - wait_until:
          mqtt.connected:
      - mqtt.publish:
          topic: "moisture-sensor/4/status"
          payload: "ready"
      - logger.log: "Sensor is ready"

ota:
  safe_mode: True
  password: !secret valve_password

mqtt:
  broker: 192.168.10.105
  username: user

logger:

  # Example configuration entry
sensor:
  - platform: adc
    pin: A0
    update_interval: 5s
    id: adc0
    on_value: 
      if:
        condition:
          mqtt.connected:
        then:
          - mqtt.publish:
              topic: "moisture-sensor/4/data"
              payload: !lambda |-
                return to_string(x);
#          - logger.log: "Moisture-sensor-1 is ready!!!!!!!!!!"
          - delay: 3s
          - deep_sleep.enter: deep_sleep_1

deep_sleep:
  id: deep_sleep_1
  run_duration: 20s
  sleep_duration: 180min
